
#  Compiler
CC =	gcc

#  Compiler Flags
CFLAGS = -Wall -O3


%.o: %.c

#Campista

#Sources
CAMPSOURCES = print.c print.h campista.c

CAMPOBJECTS = print.o campista.o

campista: $(CAMPOBJECTS)
	$(CC) -Wall -O3 $(CAMPOBJECTS)

print.o: print.h print.c
	$(CC) -Wall -O3 print.c

campista.o: print.h campista.c
	$(CC) -Wall -O3 campista.c

#clean::
#	rm -f campista.o

#depend::
#	makedepend $(SOURCES)


# DO NOT DELETE
